### PR TITLE
Fix for #80 and strip inline styling in HTML

### LINKED ISSUE #80: URL fragment sent to server
When there's a fragment in the URL, it gets sent to the server. This allowed by RFCs (only disallowed on the Web) but it's nicer to servers to not send it, since they're not allowed to use it.

### PR DESCRIPTION
**Pull request by mikejzx**
Fixes #80 even though Kristall doesn't actually handle URL fragments currently

Also strips any inline styling from HTML pages, as it can cause conflicts with the user's stylesheet. 
(e.g when visiting https://lukesmith.xyz before this patch, the page background would change colour to yellow, which may make the page unreadable in client's that are using a light font colour)

### CODE REVIEW

File: src/browsertab.cpp [hunk 1]
```diff
@@ -514,7 +514,11 @@ void BrowserTab::renderPage(const QByteArray &data, const MimeType &mime)
         document->setDefaultFont(doc_style.standard_font);
         document->setDefaultStyleSheet(doc_style.toStyleSheet());
         document->setDocumentMargin(doc_style.margin);
+
+        // Strip inline styles from page, so they don't
+        // conflict with user styles.
         QString page_html = QString::fromUtf8(data);
+        page_html.replace(QRegularExpression("<style>([^<]*)</style>"), "");
```
Comment (krkk) [inline src/browsertab.cpp:521]:
```suggestion
        page_html.replace(QRegularExpression("<style.*?>[\\S\\s]*?</style.*?>", QRegularExpression::CaseInsensitiveOption), "");
```
